/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Services.DanhMucSanPhamService;
import Services.IDanhMucSanPhamService;
import Utils.CheckData;
import ViewsModels.DanhMucSanPhamModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hieu
 */
public class FrameDanhMucSanPham extends javax.swing.JFrame {

    /**
     * Creates new form danhmuc
     */
    IDanhMucSanPhamService _iDanhMucSanPhamService;
    CheckData _check;

    public FrameDanhMucSanPham() {
        initComponents();
        _iDanhMucSanPhamService = new DanhMucSanPhamService();
        _check = new CheckData();
        loadtable();
    }

    DanhMucSanPhamModel getGuidanhmucSp() {
        return new DanhMucSanPhamModel(txt_madanhmuc.getText(), txt_tendanhmuc.getText(), tar_mota.getText());
    }

    public void loadtable() {
        DefaultTableModel _DefaultTableModel = new DefaultTableModel();
        _DefaultTableModel = (DefaultTableModel) tbl_danhmucsanpham.getModel();
        _DefaultTableModel.setRowCount(0);
        int stt = 1;
        for (DanhMucSanPhamModel x : _iDanhMucSanPhamService.getListFromDB()) {
            _DefaultTableModel.addRow(new Object[]{stt++, x.getMaDanhMuc(), x.getTenDanhMuc(), x.getMota()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_madanhmuc = new javax.swing.JTextField();
        txt_tendanhmuc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_danhmucsanpham = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tar_mota = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh mục Sản Phẩm");

        jLabel2.setText("Mã Danh Mục:");

        jLabel3.setText("Tên Danh Mục:");

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        jLabel4.setText("Mô tả:");

        tbl_danhmucsanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã danh mục", "Tên Danh Mục", "Mô Tả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_danhmucsanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl_danhmucsanphamMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_danhmucsanpham);

        tar_mota.setColumns(20);
        tar_mota.setRows(5);
        jScrollPane2.setViewportView(tar_mota);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(txt_tendanhmuc)
                    .addComponent(txt_madanhmuc)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btn_them)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_sua)
                        .addGap(17, 17, 17)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_madanhmuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(txt_tendanhmuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_sua)
                            .addComponent(btn_them)))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        if (_check.checkNullString(txt_madanhmuc.getText()) || _check.checkNullString(txt_tendanhmuc.getText()) || _check.checkNullString(txt_madanhmuc.getText())) {
            JOptionPane.showMessageDialog(this, "Không được để trống Mã và Tên");
            return;
        }
        if (_check.chekcKhoangTrang(txt_madanhmuc.getText()) || _check.checkKyTuCoDau(txt_madanhmuc.getText())) {
            JOptionPane.showMessageDialog(this, "Mã không được để khoảng trắng,có dấu và ký tự đặc biệt");
            return;
        }
        for (DanhMucSanPhamModel x : _iDanhMucSanPhamService.getListFromDB()) {
            if (x.getMaDanhMuc().equals(txt_madanhmuc.getText())) {
                JOptionPane.showMessageDialog(this, "Mã đã tồn tại!");
                return;
            }
        }
        JOptionPane.showMessageDialog(this, _iDanhMucSanPhamService.them(getGuidanhmucSp()));
        loadtable();
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        if (_check.checkNullString(txt_madanhmuc.getText()) || _check.checkNullString(txt_tendanhmuc.getText()) || _check.checkNullString(txt_madanhmuc.getText())) {
            JOptionPane.showMessageDialog(this, "Không được để trống Mã và Tên");
            return;
        }
        if (_check.chekcKhoangTrang(txt_madanhmuc.getText()) || _check.checkKyTuCoDau(txt_madanhmuc.getText())) {
            JOptionPane.showMessageDialog(this, "Mã không được để khoảng trắng,có dấu và ký tự đặc biệt");
            return;
        }
        for (DanhMucSanPhamModel x : _iDanhMucSanPhamService.getListFromDB()) {
            if (x.getMaDanhMuc().equals(txt_madanhmuc.getText())) {
                JOptionPane.showMessageDialog(this, _iDanhMucSanPhamService.sua(getGuidanhmucSp()));
                loadtable();
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "Không tìm thấy mã!");
    }//GEN-LAST:event_btn_suaActionPerformed

    private void tbl_danhmucsanphamMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_danhmucsanphamMouseReleased
        int index = tbl_danhmucsanpham.getSelectedRow();
        String Ma = tbl_danhmucsanpham.getModel().getValueAt(index, 1).toString();
        txt_madanhmuc.setText(Ma);
        txt_tendanhmuc.setText(tbl_danhmucsanpham.getModel().getValueAt(index, 2).toString());
        tar_mota.setText(tbl_danhmucsanpham.getModel().getValueAt(index, 3).toString());
        
    }//GEN-LAST:event_tbl_danhmucsanphamMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDanhMucSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDanhMucSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDanhMucSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDanhMucSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDanhMucSanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea tar_mota;
    private javax.swing.JTable tbl_danhmucsanpham;
    private javax.swing.JTextField txt_madanhmuc;
    private javax.swing.JTextField txt_tendanhmuc;
    // End of variables declaration//GEN-END:variables
}
