/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DomainModels.ChatLieu;
import Services.IManageChatLieuService;
import Services.ManageChatLieuService;
import Utils.validate;
import ViewsModel.ChatLieuModel;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hieu
 */
public class FrameChatLieu extends javax.swing.JFrame {

    private final IManageChatLieuService _iManageChatLieuService;

    private int _currentPage;
    private int _totalPages;
    private final int _pageSize;
    private long _totalProducts;

    /**
     * Creates new form chatlieu
     */
    public FrameChatLieu() {
        initComponents();
        _iManageChatLieuService = new ManageChatLieuService();
        _currentPage = 1;
        _pageSize = 10;
        loadDataToTable();
    }

    private void loadDataToTable() {
        List<ChatLieuModel> ds = _iManageChatLieuService.getProducts(_currentPage - 1, _pageSize);
        DefaultTableModel dtm = (DefaultTableModel) this.tbChatLieu.getModel();
        dtm.setRowCount(0);
        for (ChatLieuModel chatlieu : ds) {
            Object[] rowData = {
                chatlieu.getMaChatLieu(),
                chatlieu.getMota(),
                chatlieu.getTenChatLieu()};

            dtm.addRow(rowData);
        }

    }

    private void clearForm() {
        txt_machatlieu.setEnabled(true);
        txt_machatlieu.setText("");
        txt_mota.setText("");
        txt_tenchatlieu.setText("");
    }

    private ChatLieuModel getProductFromInput() {
        ChatLieuModel qlcl = new ChatLieuModel();

        String mota = txt_mota.getText();
        qlcl.setMota(mota);
        String tenchatlieu = txt_tenchatlieu.getText();
        qlcl.setTenChatLieu(tenchatlieu);

        return qlcl;
    }

    private ChatLieuModel getProductFromInput2() {
        ChatLieuModel qlcl = new ChatLieuModel();
        String machatlieu = txt_machatlieu.getText();
        qlcl.setMaChatLieu(machatlieu);
        String mota = txt_mota.getText();
        qlcl.setMota(mota);
        String tenchatlieu = txt_tenchatlieu.getText();
        qlcl.setTenChatLieu(tenchatlieu);

        return qlcl;
    }

    private String getProductIdFromSelectedRow() {
        int selectedRowIndex = tbChatLieu.getSelectedRow();
        return String.valueOf(tbChatLieu.getValueAt(selectedRowIndex, 0).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_machatlieu = new javax.swing.JTextField();
        txt_tenchatlieu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_mota = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbChatLieu = new javax.swing.JTable();
        btn_clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 255));

        jLabel1.setText("Chất liệu");

        jLabel2.setText("Mã chất liệu");

        jLabel3.setText("Tên chất liệu");

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        jLabel4.setText("Mô tả");

        txt_mota.setColumns(20);
        txt_mota.setRows(5);
        jScrollPane1.setViewportView(txt_mota);

        tbChatLieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã chất liệu", "Tên chất liệu", "Mô tả"
            }
        ));
        tbChatLieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbChatLieuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbChatLieu);

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_them))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_tenchatlieu, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_machatlieu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_machatlieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_tenchatlieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_sua)
                                    .addComponent(btn_them)
                                    .addComponent(btn_clear)))
                            .addComponent(jLabel4))
                        .addContainerGap(69, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        Object[] objects = {"co", "khong"};
        int choice = JOptionPane.showOptionDialog(this, "Xác nhận",
                "Bạn có muốn tiếp tục", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null,
                objects, objects[0]);
        if (choice == 0) {
            if (validate.checkNullText(txt_machatlieu)
                    && validate.checkNullText(txt_tenchatlieu)
                    && validate.checkNullText(txt_mota)) {
                if (validate.checkMaCL(txt_machatlieu)) {
                    ChatLieuModel clm = getProductFromInput2();
                    if (_iManageChatLieuService.insert(clm) != null) {
                        JOptionPane.showMessageDialog(this, "Thành công");
                    } else {
                        JOptionPane.showMessageDialog(this, "Thất bại");
                    }
                    loadDataToTable();
                }

            }
        }
        return;
//        if (validate.checkNullText(txt_machatlieu)
//                && validate.checkNullText(txt_tenchatlieu)
//                && validate.checkNullText(txt_mota)) {
//            if (validate.checkMaCL(txt_machatlieu)) {
//                ChatLieuModel clm = getProductFromInput2();
//                if (_iManageChatLieuService.insert(clm) != null) {
//                    JOptionPane.showMessageDialog(this, "Thành công");
//                } else {
//                    JOptionPane.showMessageDialog(this, "Thất bại");
//                }
//                loadDataToTable();
//            }
//
//        }

//        ChatLieuModel clm = getProductFromInput2();
//        if (_iManageChatLieuService.insert(clm) != null) {
//            JOptionPane.showMessageDialog(this, "Thành công");
//        } else {
//            JOptionPane.showMessageDialog(this, "Thất bại");
//        }
//        loadDataToTable();
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        Object[] objects = {"co", "khong"};
        int choice = JOptionPane.showOptionDialog(this, "Xác nhận",
                "Bạn có muốn tiếp tục", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null,
                objects, objects[0]);
        if (choice == 0) {
            if (validate.checkNullText(txt_mota)
                    && validate.checkNullText(txt_machatlieu)
                    && validate.checkNullText(txt_tenchatlieu)) {
                ChatLieuModel clm = getProductFromInput();
                String updatedProductId = getProductIdFromSelectedRow();
                clm.setMaChatLieu(updatedProductId);
                System.out.println(updatedProductId);
                if (_iManageChatLieuService.update(clm) != null) {
                    JOptionPane.showMessageDialog(this, "Thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Thất bại");
                }
                loadDataToTable();
                clearForm();
            }
        }
        return;

//        ChatLieuModel clm = getProductFromInput();
//        String updatedProductId = getProductIdFromSelectedRow();
//        clm.setMaChatLieu(updatedProductId);
//        System.out.println(updatedProductId);
//        if (_iManageChatLieuService.update(clm) != null) {
//            JOptionPane.showMessageDialog(this, "Thành công");
//        } else {
//            JOptionPane.showMessageDialog(this, "Thất bại");
//        }
//        loadDataToTable();
    }//GEN-LAST:event_btn_suaActionPerformed

    private void tbChatLieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbChatLieuMouseClicked
        int row = this.tbChatLieu.getSelectedRow();
        if (row == -1) {
            return;
        }
        String tencl = this.tbChatLieu.getValueAt(row, 1).toString();
        String mota = this.tbChatLieu.getValueAt(row, 2).toString();
        this.txt_mota.setText(mota);
        this.txt_tenchatlieu.setText(tencl);
        this.txt_machatlieu.setText(getProductIdFromSelectedRow().toString());
        this.txt_machatlieu.setEnabled(false);
    }//GEN-LAST:event_tbChatLieuMouseClicked

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        clearForm();
    }//GEN-LAST:event_btn_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameChatLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameChatLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameChatLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameChatLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameChatLieu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbChatLieu;
    private javax.swing.JTextField txt_machatlieu;
    private javax.swing.JTextArea txt_mota;
    private javax.swing.JTextField txt_tenchatlieu;
    // End of variables declaration//GEN-END:variables
}
